balls/urls.py
from django.urls import path

# 当前目录导入 views 模块
from . import views

# 设置命名空间，方便 Django 识别准确的路径
app_name = "balls"

# 列表（存储 URL 和视图函数的映射关系）
urlpatterns = [
    # "" 表示 URL 为空字符串，也就是根路径，通常代表网站的主页（如 http://localhost:8000/）
    # <int:question_id>: 从URL中捕获一个整数值，然后赋值给 question_id
    # 如果用户访问 /5/vote/ ，5 就会被捕获并赋值给 question_id
    # 然后question_id传递给对应的函数
    # detail(request=<HttpRequest object>, question_id=34)

    # path("路径表达式", 视图函数, name="名称")
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# 用户发起请求时，Django 找到名为 urlpatterns 的变量并按顺序遍历这些模式
# 例如找到 balls/ 之后，会剥离匹配的文本（"polls/"）
# 然后将剩余的文本发送给 'balls.urls' URL 配置
urlpatterns = [
    # path 最少要两个参数 route 和 view
    path('balls/', include('balls.urls')),
    path('admin/', admin.site.urls),

]

balls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin


# Create your models here.
# xxxField 确定数据类型
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )    
    # def was_published_recently(self):
    #     # 检查问题是否是在过去的 24 小时内发布， 大于等于的情况下返回 True
    #     #  datetime.timedelta(days=1) 表示时间段，为 1 天
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    # ForeignKey 定义相互之间关系， 这里每个选择都对应一个问题。
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

balls/views.py
### 视图 ###
# 在 Django 中，网页和其他内容都是从视图派生而来
# 视图函数,处理用户的 HTTP 请求，并返回一个 HTTP 响应
# request 对象包含了用户的所有请求信息
# 用户通过浏览器访问此试图函数对应的url时，Djangojiu hui就会调用这个函数

# ！！每个视图必须做到：返回一个包含被请求页面内容的 HttpResponse 对象或者抛出一个异常 ！！

from django.db.models import F
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


# 视图函数构建后，在 urls urlpatterns 中添加调用
class IndexView(generic.ListView):
    template_name = "balls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]

# 如果找不到数据库中的对象，则抛出错误


class DetailView(generic.DetailView):
    model = Question
    template_name = "balls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())    


class ResultsView(generic.DetailView):
    model = Question
    template_name = "balls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "balls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("balls:results", args=(question.id,)))

# 载入 index.html 模板文件，给它传递一个上下文(context)
# 这个上下文是一个字典，它将模板内的变量映射为 Python 对象


def index(request):
    # ORM 对象关系映射 (Object–relational mapping)
    # 按 pub_date 字段降序排列（“-”表示降序）
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    # 构建字典
    context = {"latest_question_list": latest_question_list}
    # render("请求对象", "模板文件路径", context="上下文数据字典", content_type="内容类型", status="状态码", using="模板引擎")
    return render(request, "balls/index.html", context)

balls/templates/balls/detail.html
<form action="{% url 'balls:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %} {% for choice in question.choice_set.all %}
    <input
      type="radio"
      name="choice"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
    ><br />
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote" />
</form>

balls/templates/balls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'balls/style.css' %}">

<!--使用 Django 的模板系统，只要创建一个视图，就可以将页面的设计从代码中分离出来-->
{% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li>
    <a href="{% url 'balls:detail' question.id %}"
      >{{ question.question_text }}</a
    >
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No balls are available.</p>
{% endif %}

balls/templates/balls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>
    {{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize
    }}
  </li>
  {% endfor %}
</ul>

<a href="{% url 'balls:detail' question.id %}">Vote again?</a>